version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-container
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  bank-products:
    build:
      context: ./bank-products
      args:
        NODE_ENV: ${NODE_ENV}  # Pasa el entorno al Dockerfile
    container_name: bank-products-container
    working_dir: /app
    volumes:
      - ./bank-products:/app  # Mapea el código fuente local dentro del contenedor
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./bank-products/.env  # Carga el archivo .env correspondiente
    depends_on:
      - mongo
    command: >
      sh -c "if [ ${NODE_ENV} = 'production' ]; then npm run start:prod; else npm run start:dev; fi"
    networks:
      - app-network

  bank-app:
    build:
      context: ./bank-app  # Ruta a la carpeta del frontend
      args:
        NODE_ENV: ${NODE_ENV}  # Pasa el entorno al Dockerfile
    container_name: bank-app-container
    working_dir: /app
    volumes:
      - ./bank-app:/app  # Mapea el código fuente local dentro del contenedor
      - /app/node_modules
    ports:
      - "5173:5173"  # Puerto donde corre Vite por defecto
    env_file:
      - ./bank-app/.env  # Carga el archivo .env correspondiente
    depends_on:
      - bank-products
    command: >
      sh -c "npm install && if [ \"${NODE_ENV}\" = \"production\" ]; then npm run build && npm run preview; else npm run dev; fi"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
